MACAM/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^', include('authentification.urls')),
    url(r'^constat/', include('constat_d_etat.urls')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

constat_d_etat/urls.py
from django.conf.urls import url
from django.urls import path, re_path

from . import views

app_name = 'constat'
urlpatterns = [
    url(r'^$', views.index, name="index"),

    url(r'^searchartwork/', views.search_art_work, name="search_art_work"),
    re_path(r'^previsualisation/(?P<art_type>[_a-z]*)/(?P<art_work_id>[0-9]+)/$', views.preview_art_work, name="preview_art_work"),
    re_path(r'^liste_arts/(?P<art_type>[_a-z]*)/(?P<page_number>[0-9]+)/$', views.list_arts, name="list_arts"),

    url(r'^enregistrementoeuvre', views.save_art_work, name="save_art_work"),

    re_path(r'^(?P<art_type>[_a-z]*)/(?P<art_work_id>[0-9]*)/$', views.form_report, name="form_report"),

    re_path(r'^voir_constat/(?P<art_type>[_a-z]*)/(?P<art_work_id>[0-9]*)/(?P<report_id>[0-9]*)/$', views.show_report, name="show_report"),
    re_path(r'^pdf/(?P<art_type>[_a-z]*)/(?P<art_work_id>[0-9]*)/(?P<report_id>[0-9]*)/$', views.generate_pdf_file, name="generate_pdf_file"),

]

constat_d_etat/views.py
from django.contrib.auth.decorators import login_required
from django.core import paginator
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse
from django.contrib import messages
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.core.exceptions import *

from . import forms
from .models import *
from .save.constat.save_constat_art_graphique import *
from .save.constat.save_constat_peinture_sur_toile import *
from .save.constat.save_constat_peinture_sur_bois import *
from .save.save_art import *
from .save.photo_significative.save_photo_significative import *

from authentification.models import Agent

from io import BytesIO
from django.template.loader import get_template
from xhtml2pdf import pisa


#returns page after login for constat application
@login_required(login_url='authentification:log_in')
def index(request):    
    
    """
    if not request.user.is_authenticated:
        return redirect('authentification:log_in')   
    """

    form_search = forms.FormSearchArtWork()
    return render(request, 'constat_d_etat/index.html', {'form_search': form_search})
    

#view that looks in the db for an art work according to the title or the inventory number
@login_required(login_url='authentification:log_in')
def search_art_work(request):

    form_search = forms.FormSearchArtWork(request.POST)

    if form_search.is_valid():

        #we set arts to False so that in the gabarit we can test his value
        #if it stays at False it means no art work was found and we can print a message for this
        arts = False
    
        if form_search.cleaned_data['search_by'] == 'inventory_number':

            if form_search.cleaned_data['art_type'] == forms.FormSearchArtWork.ART_GRAPHIQUE:
                arts = ArtGraphique.objects.filter(numero_inventaire=form_search.cleaned_data['query'])
    
            elif form_search.cleaned_data['art_type'] == forms.FormSearchArtWork.PEINTURE_SUR_TOILE:
                arts = PeintureSurToile.objects.filter(numero_inventaire=form_search.cleaned_data['query'])

            elif form_search.cleaned_data['art_type'] == forms.FormSearchArtWork.PEINTURE_SUR_BOIS:
                arts = PeintureSurBois.objects.filter(numero_inventaire=form_search.cleaned_data['query'])        



        elif form_search.cleaned_data['search_by'] == 'title':
            
            if form_search.cleaned_data['art_type'] == forms.FormSearchArtWork.ART_GRAPHIQUE:
                arts = ArtGraphique.objects.filter(titre__icontains=form_search.cleaned_data['query'])

            elif form_search.cleaned_data['art_type'] == forms.FormSearchArtWork.PEINTURE_SUR_TOILE:
                arts = PeintureSurToile.objects.filter(titre__icontains=form_search.cleaned_data['query'])

            elif form_search.cleaned_data['art_type'] == forms.FormSearchArtWork.PEINTURE_SUR_BOIS:
                arts = PeintureSurBois.objects.filter(titre__icontains=form_search.cleaned_data['query'])              

        art_type = form_search.cleaned_data['art_type']
        form_search = forms.FormSearchArtWork()
        context = {
            'arts': arts,
            'form_search': form_search,
            'art_type': art_type,
        }

        return render(request, 'constat_d_etat/list_art/select_art_work.html', context)

    return render(request, 'constat_d_etat/index.html', {'form_search': form_search})


@login_required(login_url='authentification:log_in')
def list_arts(request, art_type, page_number):
    arts = False
        
    if art_type == forms.FormSearchArtWork.ART_GRAPHIQUE:
        arts = ArtGraphique.objects.all()

    elif art_type == forms.FormSearchArtWork.PEINTURE_SUR_TOILE:
        arts = PeintureSurToile.objects.all()

    elif art_type == forms.FormSearchArtWork.PEINTURE_SUR_BOIS:
        arts = PeintureSurBois.objects.all()        

    if arts != False:
        paginator = Paginator(arts, 7)
        try:
            arts = paginator.page(page_number)
        except PageNotAnInteger:
            arts = paginator.page(1)
        except EmptyPage:
            arts = paginator.page(paginator.num_pages)

    form_search = forms.FormSearchArtWork()
    context = {
        'arts': arts,
        'form_search': form_search,
        'art_type': art_type,
    }

    return render(request, 'constat_d_etat/list_art/list_arts.html', context)


#returns a page to see the different options we have on the art work selected
@login_required(login_url='authentification:log_in')
def preview_art_work(request, art_type, art_work_id):    
    
    if art_type == forms.FormSearchArtWork.ART_GRAPHIQUE:
        art = get_object_or_404(ArtGraphique, id=int(art_work_id))
        reports = ConstatArtGraphique.objects.filter(art_graphique=art).order_by('-date')

    elif art_type == forms.FormSearchArtWork.PEINTURE_SUR_TOILE:
        art = get_object_or_404(PeintureSurToile, id=int(art_work_id))
        reports = ConstatPeintureSurToile.objects.filter(peinture_sur_toile=art).order_by('-date')

    elif art_type == forms.FormSearchArtWork.PEINTURE_SUR_BOIS:
        art = get_object_or_404(PeintureSurBois, id=int(art_work_id))
        reports = ConstatPeintureSurBois.objects.filter(peinture_sur_bois=art).order_by('-date')    

    form_search = forms.FormSearchArtWork()
    context = {
        'art': art,
        'form_search': form_search,
        'art_type': art_type,
        'reports': reports,
    }

    return render(request, 'constat_d_etat/preview_art_work/preview_art_work.html', context)

    

    
#returns a page to save an art work if the method is GET
#save an art work if the method is POST
@login_required(login_url='authentification:log_in')
def save_art_work(request):
    
    if request.method == 'GET':
        form = forms.FormArt()
        return render(request, 'constat_d_etat/forms/save_art.html', {'form': form})

    else:
        form = forms.FormArt(request.POST, request.FILES)

        if form.is_valid():
            art_saver = SaveArt(form.cleaned_data)
            print(request.FILES)

            if form.cleaned_data['type_oeuvre'] == forms.FormArt.ART_GRAPHIQUE:
                art_saver.save_art_graphique()

            elif form.cleaned_data['type_oeuvre'] == forms.FormArt.PEINTURE_SUR_BOIS:
                art_saver.save_peinture_sur_bois()

            elif form.cleaned_data['type_oeuvre'] == forms.FormArt.PEINTURE_SUR_TOILE:
                art_saver.save_peinture_sur_toile()

            return redirect('constat:index')

        return render(request, 'constat_d_etat/forms/save_art.html', {'form': form})



#returns a page to make a report if the method is GET
#save a report if the method is POST
@login_required(login_url='authentification:log_in')
def form_report(request, art_type, art_work_id):

    agent = False

    try:
        agent = Agent.objects.get(user_id=request.user.id)
    except ObjectDoesNotExist:
        pass
    
    context = {
        'art_type': art_type,
        'agent': agent,
    }

    if request.method == 'GET':        

        if art_type == forms.FormArt.ART_GRAPHIQUE:
            form = forms.FormArtGraphique()
            art = get_object_or_404(ArtGraphique, id=int(art_work_id))
            
            context['art'] = art
            context['form'] = form                
            #context['form_art'] = form_art  

            form = forms.FormArtGraphique()
            return render(request, 'constat_d_etat/forms/form_art_graphique.html', context)
            

        elif art_type == forms.FormArt.PEINTURE_SUR_TOILE:
            form = forms.FormPeintureSurToile()
            art = get_object_or_404(PeintureSurToile, id=int(art_work_id))
            
            context['art'] = art
            context['form'] = form                
            #context['form_art'] = form_art
            
            form = forms.FormPeintureSurToile()
            return render(request, 'constat_d_etat/forms/form_peinture_sur_toile.html', context)


        elif art_type == forms.FormArt.PEINTURE_SUR_BOIS:
            form = forms.FormPeintureSurBois()
            art = get_object_or_404(PeintureSurBois, id=int(art_work_id))
            
            context['art'] = art
            context['form'] = form                
            #context['form_art'] = form_art

            form = forms.FormPeintureSurBois()
            return render(request, 'constat_d_etat/forms/form_peinture_sur_bois.html', context)
   

    else:
        if art_type == forms.FormArt.ART_GRAPHIQUE:
            form = forms.FormArtGraphique(request.POST)            
            art = get_object_or_404(ArtGraphique, id=int(art_work_id))

            if form.is_valid():
                form.cleaned_data['constat_auteur_constat'] = request.POST['report_author']
                if agent != False:
                    form.cleaned_data['signature_auteur_constat'] = agent.signature
                else:
                    form.cleaned_data['signature_auteur_constat'] = None

                constat_saver = SaveConstatArtGraphique(form.cleaned_data, int(art_work_id))
                constat = constat_saver.save_constat_art_graphique()

                photo_significative_saver = SavePhotoSignificative(request.POST, request.FILES, constat)
                photo_significative_saver.save_photo_significative_cadre()
                photo_significative_saver.save_photo_significative_support_art_graphique()

                messages.add_message(request, messages.SUCCESS, 'Constat effectué')
                return redirect('constat:preview_art_work', art_type=art_type, art_work_id=art_work_id)

            context['art'] = art
            context['form'] = form                
            #context['form_art'] = form_art

            return render(request, 'constat_d_etat/forms/form_art_graphique.html', context)

        elif art_type == forms.FormArt.PEINTURE_SUR_TOILE:

constat_d_etat/templates/constat_d_etat/preview_art_work/preview_art_work.html
<!DOCTYPE html>

<html>

    <head>
        {% load static %}
        <link rel="stylesheet" type="text/css" href="{% static 'constat_d_etat/css/nav_bar_style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'constat_d_etat/css/list_art_style.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'constat_d_etat/css/preview-art-style.css' %}" />
        <script src="{% static 'constat_d_etat/js/show_nav_bar.js' %}" defer></script>
    </head>

    <body>

        {% include 'constat_d_etat/template_nav_bar.html' %}

        <div class="principal">

            <div class="box">   
                {% include 'constat_d_etat/forms/form_search_art.html'%} 
            </div>
            
            <div class="list-arts">
                <table>
                    <tr>
                        {% if art.photo_face.url != "" %}
                            <td><a href="{{ art.photo_face.url }}"><img src="{{ art.photo_face.url }}" width="220" height="250"></a></td>
                        {% else %}
                                <td><img src="{% static 'constat_d_etat/img/image-missing.jpg' %}" width="220" height="250"></td>
                        {% endif %}
                        
                        {% if art.photo_revers.url != "" %}
                            <td><a href="{{ art.photo_revers.url }}"><img src="{{ art.photo_revers.url }}" width="220" height="250"></a></td>
                        {% else %}
                                <td><img src="{% static 'constat_d_etat/img/image-missing.jpg' %}" width="220" height="250"></td>
                        {% endif %}
                    </tr>
                </table>

                <table>
                    <tr>
                        <td><label>Numéro d'inventaire : </label></td>
                        <td>{{ art.numero_inventaire }}</td>
                    </tr>
                    <tr>
                        <td><label>Titre : </label></td>
                        <td>{{ art.titre }}</td>
                    </tr>
                    <tr>
                        <td><label>Auteur : </label></td>
                        <td>{{ art.auteur }}</td>
                    </tr>
                    <tr>
                        <td><label>Format : </label></td>
                        <td>{{ art.format_oeuvre }}</td>
                    </tr>
                    <tr>
                        <td><label>Dimensions : </label></td>
                        <td>{{ art.largeur_sans_cadre }}cm x {{ art.hauteur_sans_cadre }}cm</td>
                    </tr>
                </table>

                <a href="{% url 'constat:form_report' art_type=art_type art_work_id=art.id %}"><button class="btn">Nouveau constat</button></a>
            </div>
            
            <table class="report-list">
                <thead>
                    <th>Date</th>
                    <th>Auteur</th>
                    <th>Consulter</th>
                    <th>PDF</th>
                </thead>
            {% for report in reports %}

                <hr>

                <tr>
                    <td>{{ report.date }}</td>
                    <td>{{ report.auteur }}</td>
                    <td><a href="{% url 'constat:show_report' art_type=art_type art_work_id=art.id report_id=report.id %}"><button class="btn">Voir</button></a></td>
                    <td><a href="{% url 'constat:generate_pdf_file' art_type=art_type art_work_id=art.id report_id=report.id %}"><button class="btn">pdf</button></a></td>
                </tr>                

            {% endfor %}
            </table>

            {% if messages %}
            <ul class="messages">
                {% for message in messages %}
                <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
                {% endfor %}
            </ul>
            {% endif %}
        </div>

    </body>

</html>