MACAM/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    url(r'^', include('authentification.urls')),
    url(r'^constat/', include('constat_d_etat.urls')),
    url(r'^admin/', admin.site.urls),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

constat_d_etat/urls.py
from django.conf.urls import url
from django.urls import path, re_path

from . import views

app_name = 'constat'
urlpatterns = [
    url(r'^$', views.index, name="index"),

    url(r'^searchartwork/', views.search_art_work, name="search_art_work"),
    re_path(r'^previsualisation/(?P<art_type>[_a-z]*)/(?P<art_work_id>[0-9]+)/$', views.preview_art_work, name="preview_art_work"),
    re_path(r'^liste_arts/(?P<art_type>[_a-z]*)/(?P<page_number>[0-9]+)/$', views.list_arts, name="list_arts"),

    url(r'^enregistrementoeuvre', views.save_art_work, name="save_art_work"),

    re_path(r'^(?P<art_type>[_a-z]*)/(?P<art_work_id>[0-9]*)/$', views.form_report, name="form_report"),

    re_path(r'^voir_constat/(?P<art_type>[_a-z]*)/(?P<art_work_id>[0-9]*)/(?P<report_id>[0-9]*)/$', views.show_report, name="show_report"),
    re_path(r'^pdf/(?P<art_type>[_a-z]*)/(?P<art_work_id>[0-9]*)/(?P<report_id>[0-9]*)/$', views.generate_pdf_file, name="generate_pdf_file"),

]

constat_d_etat/views.py
from django.contrib.auth.decorators import login_required
from django.core import paginator
from django.shortcuts import redirect, render, get_object_or_404
from django.http import HttpResponse
from django.contrib import messages
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.core.exceptions import *

from . import forms
from .models import *
from .save.constat.save_constat_art_graphique import *
from .save.constat.save_constat_peinture_sur_toile import *
from .save.constat.save_constat_peinture_sur_bois import *
from .save.save_art import *
from .save.photo_significative.save_photo_significative import *

from authentification.models import Agent

from io import BytesIO
from django.template.loader import get_template
from xhtml2pdf import pisa


#returns page after login for constat application
@login_required(login_url='authentification:log_in')
def index(request):    
    
    """
    if not request.user.is_authenticated:
        return redirect('authentification:log_in')   
    """

    form_search = forms.FormSearchArtWork()
    return render(request, 'constat_d_etat/index.html', {'form_search': form_search})
    

#view that looks in the db for an art work according to the title or the inventory number
@login_required(login_url='authentification:log_in')
def search_art_work(request):

    form_search = forms.FormSearchArtWork(request.POST)

    if form_search.is_valid():

        #we set arts to False so that in the gabarit we can test his value
        #if it stays at False it means no art work was found and we can print a message for this
        arts = False
    
        if form_search.cleaned_data['search_by'] == 'inventory_number':

            if form_search.cleaned_data['art_type'] == forms.FormSearchArtWork.ART_GRAPHIQUE:
                arts = ArtGraphique.objects.filter(numero_inventaire=form_search.cleaned_data['query'])
    
            elif form_search.cleaned_data['art_type'] == forms.FormSearchArtWork.PEINTURE_SUR_TOILE:
                arts = PeintureSurToile.objects.filter(numero_inventaire=form_search.cleaned_data['query'])

            elif form_search.cleaned_data['art_type'] == forms.FormSearchArtWork.PEINTURE_SUR_BOIS:
                arts = PeintureSurBois.objects.filter(numero_inventaire=form_search.cleaned_data['query'])        



        elif form_search.cleaned_data['search_by'] == 'title':
            
            if form_search.cleaned_data['art_type'] == forms.FormSearchArtWork.ART_GRAPHIQUE:
                arts = ArtGraphique.objects.filter(titre__icontains=form_search.cleaned_data['query'])

            elif form_search.cleaned_data['art_type'] == forms.FormSearchArtWork.PEINTURE_SUR_TOILE:
                arts = PeintureSurToile.objects.filter(titre__icontains=form_search.cleaned_data['query'])

            elif form_search.cleaned_data['art_type'] == forms.FormSearchArtWork.PEINTURE_SUR_BOIS:
                arts = PeintureSurBois.objects.filter(titre__icontains=form_search.cleaned_data['query'])              

        art_type = form_search.cleaned_data['art_type']
        form_search = forms.FormSearchArtWork()
        context = {
            'arts': arts,
            'form_search': form_search,
            'art_type': art_type,
        }

        return render(request, 'constat_d_etat/list_art/select_art_work.html', context)

    return render(request, 'constat_d_etat/index.html', {'form_search': form_search})


@login_required(login_url='authentification:log_in')
def list_arts(request, art_type, page_number):
    arts = False
        
    if art_type == forms.FormSearchArtWork.ART_GRAPHIQUE:
        arts = ArtGraphique.objects.all()

    elif art_type == forms.FormSearchArtWork.PEINTURE_SUR_TOILE:
        arts = PeintureSurToile.objects.all()

    elif art_type == forms.FormSearchArtWork.PEINTURE_SUR_BOIS:
        arts = PeintureSurBois.objects.all()        

    if arts != False:
        paginator = Paginator(arts, 7)
        try:
            arts = paginator.page(page_number)
        except PageNotAnInteger:
            arts = paginator.page(1)
        except EmptyPage:
            arts = paginator.page(paginator.num_pages)

    form_search = forms.FormSearchArtWork()
    context = {
        'arts': arts,
        'form_search': form_search,
        'art_type': art_type,
    }

    return render(request, 'constat_d_etat/list_art/list_arts.html', context)


#returns a page to see the different options we have on the art work selected
@login_required(login_url='authentification:log_in')
def preview_art_work(request, art_type, art_work_id):    
    
    if art_type == forms.FormSearchArtWork.ART_GRAPHIQUE:
        art = get_object_or_404(ArtGraphique, id=int(art_work_id))
        reports = ConstatArtGraphique.objects.filter(art_graphique=art).order_by('-date')

    elif art_type == forms.FormSearchArtWork.PEINTURE_SUR_TOILE:
        art = get_object_or_404(PeintureSurToile, id=int(art_work_id))
        reports = ConstatPeintureSurToile.objects.filter(peinture_sur_toile=art).order_by('-date')

    elif art_type == forms.FormSearchArtWork.PEINTURE_SUR_BOIS:
        art = get_object_or_404(PeintureSurBois, id=int(art_work_id))
        reports = ConstatPeintureSurBois.objects.filter(peinture_sur_bois=art).order_by('-date')    

    form_search = forms.FormSearchArtWork()
    context = {
        'art': art,
        'form_search': form_search,
        'art_type': art_type,
        'reports': reports,
    }

    return render(request, 'constat_d_etat/preview_art_work/preview_art_work.html', context)

    

    
#returns a page to save an art work if the method is GET
#save an art work if the method is POST
@login_required(login_url='authentification:log_in')
def save_art_work(request):
    
    if request.method == 'GET':
        form = forms.FormArt()
        return render(request, 'constat_d_etat/forms/save_art.html', {'form': form})

    else:
        form = forms.FormArt(request.POST, request.FILES)

        if form.is_valid():
            art_saver = SaveArt(form.cleaned_data)
            print(request.FILES)

            if form.cleaned_data['type_oeuvre'] == forms.FormArt.ART_GRAPHIQUE:
                art_saver.save_art_graphique()

            elif form.cleaned_data['type_oeuvre'] == forms.FormArt.PEINTURE_SUR_BOIS:
                art_saver.save_peinture_sur_bois()

            elif form.cleaned_data['type_oeuvre'] == forms.FormArt.PEINTURE_SUR_TOILE:
                art_saver.save_peinture_sur_toile()

            return redirect('constat:index')

        return render(request, 'constat_d_etat/forms/save_art.html', {'form': form})



#returns a page to make a report if the method is GET
#save a report if the method is POST
@login_required(login_url='authentification:log_in')
def form_report(request, art_type, art_work_id):

    agent = False

    try:
        agent = Agent.objects.get(user_id=request.user.id)
    except ObjectDoesNotExist:
        pass
    
    context = {
        'art_type': art_type,
        'agent': agent,
    }

    if request.method == 'GET':        

        if art_type == forms.FormArt.ART_GRAPHIQUE:
            form = forms.FormArtGraphique()
            art = get_object_or_404(ArtGraphique, id=int(art_work_id))
            
            context['art'] = art
            context['form'] = form                
            #context['form_art'] = form_art  

            form = forms.FormArtGraphique()
            return render(request, 'constat_d_etat/forms/form_art_graphique.html', context)
            

        elif art_type == forms.FormArt.PEINTURE_SUR_TOILE:
            form = forms.FormPeintureSurToile()
            art = get_object_or_404(PeintureSurToile, id=int(art_work_id))
            
            context['art'] = art
            context['form'] = form                
            #context['form_art'] = form_art
            
            form = forms.FormPeintureSurToile()
            return render(request, 'constat_d_etat/forms/form_peinture_sur_toile.html', context)


        elif art_type == forms.FormArt.PEINTURE_SUR_BOIS:
            form = forms.FormPeintureSurBois()
            art = get_object_or_404(PeintureSurBois, id=int(art_work_id))
            
            context['art'] = art
            context['form'] = form                
            #context['form_art'] = form_art

            form = forms.FormPeintureSurBois()
            return render(request, 'constat_d_etat/forms/form_peinture_sur_bois.html', context)
   

    else:
        if art_type == forms.FormArt.ART_GRAPHIQUE:
            form = forms.FormArtGraphique(request.POST)            
            art = get_object_or_404(ArtGraphique, id=int(art_work_id))

            if form.is_valid():
                form.cleaned_data['constat_auteur_constat'] = request.POST['report_author']
                if agent != False:
                    form.cleaned_data['signature_auteur_constat'] = agent.signature
                else:
                    form.cleaned_data['signature_auteur_constat'] = None

                constat_saver = SaveConstatArtGraphique(form.cleaned_data, int(art_work_id))
                constat = constat_saver.save_constat_art_graphique()

                photo_significative_saver = SavePhotoSignificative(request.POST, request.FILES, constat)
                photo_significative_saver.save_photo_significative_cadre()
                photo_significative_saver.save_photo_significative_support_art_graphique()

                messages.add_message(request, messages.SUCCESS, 'Constat effectué')
                return redirect('constat:preview_art_work', art_type=art_type, art_work_id=art_work_id)

            context['art'] = art
            context['form'] = form                
            #context['form_art'] = form_art

            return render(request, 'constat_d_etat/forms/form_art_graphique.html', context)

        elif art_type == forms.FormArt.PEINTURE_SUR_TOILE:

constat_d_etat/templates/constat_d_etat/forms/form_search_art.html
<form action="{% url 'constat:search_art_work' %}" method="POST" class="form-search-art">
    {% csrf_token %} 
    
    <div class="criterion">
        <label>Type oeuvre d'art : </label>                        
        {{ form_search.art_type }}

        <label>Recherche par : </label>
        {{ form_search.search_by }}
    </div>

    <div class="search-bar">
        {{ form_search.query }}
        <input type="submit" value="Recherche">   
    </div> 
    
</form>    

constat_d_etat/templates/constat_d_etat/forms/save_art.html
<!DOCTYPE html>

<html>

    <head>
        {% load static %}
        <title>{% block title %}{% endblock %}</title>        
        <link rel="stylesheet" type="text/css" href="{% static 'constat_d_etat/css/template_style2.css' %}" />
        <link rel="stylesheet" type="text/css" href="{% static 'constat_d_etat/css/save_art_style.css' %}" />  
    </head>

    <body>

        <div class="principal">
            
            <form method="POST" id="first" enctype="multipart/form-data" action="{% block form_action %}{% endblock %}">
                {% csrf_token %}
                {{ form.non_field_errors }}

                <div id="photos">
                    <a href="{% url 'constat:index' %}"><img src="{% static 'constat_d_etat/img/logo1.png' %}"></a>

                    <h2>Oeuvre d'art</h2>

                    <table id="id-pic-table">
                        <tr>
                            <td colspan="2">Photos d' idendification</td>
                        </tr>
                        <tr>
                            <td>Face</td>
                            <td>Revers</td>
                        </tr>
                        <tr class="pic-row">
                            {{ form.photo_oeuvre_face.errors }}
                            <td>{{ form.photo_oeuvre_face }}</td>
                            {{ form.photo_oeuvre_revers.errors }}
                            <td>{{ form.photo_oeuvre_revers }}</td>
                        </tr>
                    </table>
                </div>            

                <div class="to-border">
                    <div id="informations">
                        <table>
                            <tr>
                                {{ form.institution.errors }}
                                <td><label class="label-bold" for="{{ form.institution.id_for_label }}">{{ form.institution.label }}</label></td>
                                <td>{{ form.institution }}</td>
                            </tr>

                            <tr>
                                {{ form.numero_inventaire.errors }}
                                <td><label class="label-bold" for="{{ form.numero_inventaire.id_for_label }}">{{ form.numero_inventaire.label }}<label></td>
                                <td>{{ form.numero_inventaire }}</td>                                
                            </tr>

                            <tr>
                                {{ form.titre_oeuvre.errors }}
                                <td><label class="label-bold" for="{{ form.titre_oeuvre.id_for_label }}">{{ form.titre_oeuvre.label }}</label></td>
                                <td>{{ form.titre_oeuvre }}</td>

                                <td><label class="label-bold" for="{{ form.type_oeuvre.id_for_label }}">{{ form.type_oeuvre.label }}</label></td>
                                <td>{{ form.type_oeuvre }}</td>                            </tr>

                            <tr>
                                {{ form.auteur_oeuvre.errors }}
                                <td><label class="label-bold" for="{{ form.auteur_oeuvre.id_for_label }}">{{ form.auteur_oeuvre.label }}</label></td>
                                <td>{{ form.auteur_oeuvre }}</td>
                            </tr>
                        </table>                

                        <table>
                            <tr>
                                <td><label class="label-bold">Dimensions : </label></td>
                            </tr>

                            <tr>
                                <td></td>
                                <td><label>Hauteur</label></td>
                                <td><label>Largeur</label></td>
                                <td><label>Epaisseur</label></td>
                            </tr>

                            <tr>
                                <td><label>Avec cadre : </label></td>
                                <td>{{ form.hauteur_avec_cadre }}<label>cm</label></td>
                                <td>{{ form.largeur_avec_cadre }}<label>cm</label></td>
                                <td>{{ form.epaisseur_avec_cadre }}<label>cm</label></td>
                            </tr>

                            <tr>
                            <td><label>Sans cadre : </label></td>
                                <td>{{ form.hauteur_sans_cadre }}<label>cm</label></td>
                                <td>{{ form.largeur_sans_cadre }}<label>cm</label></td>
                                <td>{{ form.epaisseur_sans_cadre }}<label>cm</label></td>
                            </tr>

                            <tr><td><label class="label-bold">Format : </label></td></tr>
                        </table>                

                        <table>
                            <tr>
                                <td>{{ form.format_oeuvre }}</td> 
                                <td>{{ form.autre_format }}</td>                                
                            </tr>
                        </table>
                    </div>
                </div>

                <input type="submit" value="Enregistrer">

            </form>
        </div>
    </body>
</html>

constat_d_etat/templates/constat_d_etat/forms/template_peinture.html
{% extends 'constat_d_etat/forms/template_art.html' %}

{% block option1 %}

<div id="couche_picturale">

    <h4>Couche picturale</h4>

    <div class="to-border-tr">
        <table>

            <caption>Altérations optiques</caption>
            
            <tr>
                <td>{{ form.peinture_alterations_optiques_usures }} <label for="{{ form.peinture_alterations_optiques_usures.id_for_label }}">{{ form.peinture_alterations_optiques_usures.label }}</label></td>
                <td>{{ form.peinture_alterations_optiques_griffures }} <label for="{{ form.peinture_alterations_optiques_griffures.id_for_label }}">{{ form.peinture_alterations_optiques_griffures.label }}</label></td>
                <td>{{ form.peinture_alterations_optiques_impression_texture }} <label for="{{ form.peinture_alterations_optiques_impression_texture.id_for_label }}">{{ form.peinture_alterations_optiques_impression_texture.label }}</label></td>
            </tr>
            <tr>
                <td>{{ form.peinture_alterations_optiques_marques_chassis }} <label for="{{ form.peinture_alterations_optiques_marques_chassis.id_for_label }}">{{ form.peinture_alterations_optiques_marques_chassis.label }}</label></td>
                <td>{{ form.peinture_alterations_optiques_trous_envol }} <label for="{{ form.peinture_alterations_optiques_trous_envol.id_for_label }}">{{ form.peinture_alterations_optiques_trous_envol.label }}</label></td>
                <td>{{ form.peinture_alterations_optiques_dejections_insectes }} <label for="{{ form.peinture_alterations_optiques_dejections_insectes.id_for_label }}">{{ form.peinture_alterations_optiques_dejections_insectes.label }}</label></td>
            </tr>
            <tr>
                <td>{{ form.peinture_alterations_optiques_transparences_accrues }} <label for="{{ form.peinture_alterations_optiques_transparences_accrues.id_for_label }}">{{ form.peinture_alterations_optiques_transparences_accrues.label }}</label></td>
                <td>{{ form.peinture_alterations_optiques_repeints_alteres }} <label for="{{ form.peinture_alterations_optiques_repeints_alteres.id_for_label }}">{{ form.peinture_alterations_optiques_repeints_alteres.label }}</label></td>
                <td>{{ form.peinture_alterations_optiques_matics_debordants }} <label for="{{ form.peinture_alterations_optiques_matics_debordants.id_for_label }}">{{ form.peinture_alterations_optiques_matics_debordants.label }}</label></td>
            </tr>
            <tr>
                <td>{{ form.peinture_alterations_optiques_traces_de_dorure }} <label for="{{ form.peinture_alterations_optiques_traces_de_dorure.id_for_label }}">{{ form.peinture_alterations_optiques_traces_de_dorure.label }}</label></td>
                <td>{{ form.peinture_alterations_optiques_projections }} <label for="{{ form.peinture_alterations_optiques_projections.id_for_label }}">{{ form.peinture_alterations_optiques_projections.label }}</label></td>
                <td>{{ form.peinture_alterations_optiques_ecrasement_de_matiere }} <label for="{{ form.peinture_alterations_optiques_ecrasement_de_matiere.id_for_label }}">{{ form.peinture_alterations_optiques_ecrasement_de_matiere.label }}</label></td>
            </tr>

        </table>

        <table>
            <p class="sub-caption">Vernis</p>

            <tr>
                <td></td>
                <td></td>
                <td></td>
                <td colspan="2">{{ form.peinture_vernis_homogeneite_satisfaisante }} <label for="{{ form.peinture_vernis_homogeneite_satisfaisante.id_for_label }}">{{ form.peinture_vernis_homogeneite_satisfaisante.label }}</label></td>
            </tr>
            <tr>
                <td>{{ form.peinture_vernis_jaunissement }} <label for="{{ form.peinture_vernis_jaunissement.id_for_label }}">{{ form.peinture_vernis_jaunissement.label }}</label></td>
                <td>{{ form.peinture_vernis_encrassement }} <label for="{{ form.peinture_vernis_encrassement.id_for_label }}">{{ form.peinture_vernis_encrassement.label }}</label></td>
                <td>{{ form.peinture_vernis_chancis }} <label for="{{ form.peinture_vernis_chancis.id_for_label }}">{{ form.peinture_vernis_chancis.label }}</label></td>
                <td>{{ form.peinture_vernis_coulures }} <label for="{{ form.peinture_vernis_coulures.id_for_label }}">{{ form.peinture_vernis_coulures.label }}</label></td>
            </tr>

            <tr>
                <td>{{ form.peinture_vernis_inegalite_de_surface }} <label for="{{ form.peinture_vernis_inegalite_de_surface.id_for_label }}">{{ form.peinture_vernis_inegalite_de_surface.label }}</label></td>
                <td>{{ form.peinture_vernis_lacunes }} <label for="{{ form.peinture_vernis_lacunes.id_for_label }}">{{ form.peinture_vernis_lacunes.label }}</label></td>
                <td>{{ form.peinture_vernis_soulevements }} <label for="{{ form.peinture_vernis_soulevements.id_for_label }}">{{ form.peinture_vernis_soulevements.label }}</label></td>
                <td>{{ form.peinture_vernis_chevauchement_ecaillement }} <label for="{{ form.peinture_vernis_chevauchement_ecaillement.id_for_label }}">{{ form.peinture_vernis_chevauchement_ecaillement.label }}</label></td>
            </tr>
        </table>

        <table>

            <caption>Adhésion</caption>

            <tr>
                <td></td>
                <td></td>
                <td colspan="2">{{ form.peinture_adhesion_satisfaisante }} <label for="{{ form.peinture_adhesion_satisfaisante.id_for_label }}">{{ form.peinture_adhesion_satisfaisante.label }}</label></td>
            </tr>

            <tr>
                <td>{{ form.peinture_adhesion_deplacage }} <label for="{{ form.peinture_adhesion_deplacage.id_for_label }}">{{ form.peinture_adhesion_deplacage.label }}</label></td>
                <td>{{ form.peinture_adhesion_epidermage }} <label for="{{ form.peinture_adhesion_epidermage.id_for_label }}">{{ form.peinture_adhesion_epidermage.label }}</label></td>
                <td>{{ form.peinture_adhesion_cloque }} <label for="{{ form.peinture_adhesion_cloque.id_for_label }}">{{ form.peinture_adhesion_cloque.label }}</label></td>
                <td>{{ form.peinture_adhesion_deplacement_ecailles }} <label for="{{ form.peinture_adhesion_deplacement_ecailles.id_for_label }}">{{ form.peinture_adhesion_deplacement_ecailles.label }}</label></td>
            </tr>

            <tr>
                <td>{{ form.peinture_adhesion_zones_pulverilentes }} <label for="{{ form.peinture_adhesion_zones_pulverilentes.id_for_label }}">{{ form.peinture_adhesion_zones_pulverilentes.label }}</label></td>
                <td>{{ form.peinture_adhesion_transposition }} <label for="{{ form.peinture_adhesion_transposition.id_for_label }}">{{ form.peinture_adhesion_transposition.label }}</label></td>
                <td>{{ form.peinture_adhesion_brulures }} <label for="{{ form.peinture_adhesion_brulures.id_for_label }}">{{ form.peinture_adhesion_brulures.label }}</label></td>
                <td>{{ form.peinture_adhesion_lacunes }} <label for="{{ form.peinture_adhesion_lacunes.id_for_label }}">{{ form.peinture_adhesion_lacunes.label }}</label></td>
            </tr>

            <tr>
                <td>{{ form.peinture_adhesion_soulevement }} <label for="{{ form.peinture_adhesion_soulevement.id_for_label }}">{{ form.peinture_adhesion_soulevement.label }}</label></td>
                <td>{{ form.peinture_adhesion_chevauchement_ecailles }} <label for="{{ form.peinture_adhesion_chevauchement_ecailles.id_for_label }}">{{ form.peinture_adhesion_chevauchement_ecailles.label }}</label></td>
            </tr>

        </table>

        <table>

            <caption>Cohésion</caption>

            <p class="sub-caption">Craquelures prématurées: </p>

            <tr>
                <td>{{ form.peinture_craquelure_prematuree_rides }} <label for="{{ form.peinture_craquelure_prematuree_rides.id_for_label }}">{{ form.peinture_craquelure_prematuree_rides.label }}</label></td>
                <td>{{ form.peinture_craquelure_prematuree_gercures }} <label for="{{ form.peinture_craquelure_prematuree_gercures.id_for_label }}">{{ form.peinture_craquelure_prematuree_gercures.label }}</label></td>
                <td>{{ form.peinture_craquelure_prematuree_crevasses }} <label for="{{ form.peinture_craquelure_prematuree_crevasses.id_for_label }}">{{ form.peinture_craquelure_prematuree_crevasses.label }}</label></td>
                <td>{{ form.peinture_craquelure_prematuree_craquelures_fermees }} <label for="{{ form.peinture_craquelure_prematuree_craquelures_fermees.id_for_label }}">{{ form.peinture_craquelure_prematuree_craquelures_fermees.label }}</label></td>
            </tr>                           

        </table>

        <table>

            <p class="sub-caption">Craquelures d'âge :</p>

            <tr>
                <td colspan="2">{{ form.peinture_craquelure_age_reseau_generalise_fin }} <label for="{{ form.peinture_craquelure_age_reseau_generalise_fin.id_for_label }}">{{ form.peinture_craquelure_age_reseau_generalise_fin.label }}</label></td>
                <td colspan="2">{{ form.peinture_craquelure_age_reseau_generalise_prononce }} <label for="{{ form.peinture_craquelure_age_reseau_generalise_prononce.id_for_label }}">{{ form.peinture_craquelure_age_reseau_generalise_prononce.label }}</label></td>
            </tr>

            <tr>
                <td>{{ form.peinture_craquelure_age_limites_a_une_zone }} <label for="{{ form.peinture_craquelure_age_limites_a_une_zone.id_for_label }}">{{ form.peinture_craquelure_age_limites_a_une_zone.label }}</label></td>
                <td>{{ form.peinture_craquelure_age_circulaire }} <label for="{{ form.peinture_craquelure_age_circulaire.id_for_label }}">{{ form.peinture_craquelure_age_circulaire.label }}</label></td>
                <td>{{ form.peinture_craquelure_age_diagonales }} <label for="{{ form.peinture_craquelure_age_diagonales.id_for_label }}">{{ form.peinture_craquelure_age_diagonales.label }}</label></td>
                <td>{{ form.peinture_craquelure_age_horizontales_verticales }} <label for="{{ form.peinture_craquelure_age_horizontales_verticales.id_for_label }}">{{ form.peinture_craquelure_age_horizontales_verticales.label }}</label></td>
            </tr>

            <tr>
                <td>{{ form.peinture_craquelure_age_en_echelle }} <label for="{{ form.peinture_craquelure_age_en_echelle.id_for_label }}">{{ form.peinture_craquelure_age_en_echelle.label }}</label></td>
                <td>{{ form.peinture_craquelure_age_en_escargot }} <label for="{{ form.peinture_craquelure_age_en_escargot.id_for_label }}">{{ form.peinture_craquelure_age_en_escargot.label }}</label></td>
                <td>{{ form.peinture_craquelure_age_faiencage }} <label for="{{ form.peinture_craquelure_age_faiencage.id_for_label }}">{{ form.peinture_craquelure_age_faiencage.label }}</label></td>
                <td>{{ form.peinture_craquelure_age_pavimenteuses }} <label for="{{ form.peinture_craquelure_age_pavimenteuses.id_for_label }}">{{ form.peinture_craquelure_age_pavimenteuses.label }}</label></td>
            </tr>                    

        </table>
    </div>

    <div>
        <table id="tab-photos-significatives-couche-picturale">

            <caption>Photos significatives</caption>

            <input type="button" id="btn-photos-significatives-couche-picturale" value="Ajouter photo">

            <tr>
                <td>Photo de détail</td>
                <td>Emplacement</td>
            </tr>
            
        </table>

        <input value="0" name="nombre-photos-significatives-couche-picturale" id="nombre-photos-significatives-couche-picturale" hidden>
    </div>
</div>

<!-- Place to put the pics of alterations -->
{% block alteration_pic_adhesion %}{% endblock %}

{% endblock%}